import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJs Database Connection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="m-16">
          <div className="my-10">
            <h2>Demo Database</h2>
            <ul className="list-decimal pl-10">
              <li>
                <Link href="/">MySQL</Link>
              </li>
            </ul>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
